### ISSUE TITLE
The answer is wrong

### ISSUE THREAD

**Issue by alai04** [howtographql/howtographql#1189] opened 2020-11-12 09:28 UTC
In https://github.com/howtographql/howtographql/blob/master/content/backend/graphql-js/8-filtering-pagination-and-sorting.md, the answer of question is wrong. The correct answer should be 0.

**Comment by masonlouchart** [comment] 2021-01-11 23:07
Duplicate of #1180

**Closed** 2021-01-12 00:41 UTC
