### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [howtographql/howtographql#65] opened 2017-07-11 20:56 UTC
Navigating in chrome browser to https://www.howtographql.com/?v1 gives NET::ERR_CERT_AUTHORITY_INVALID

**Comment by timsuchanek** [comment] 2017-07-12 12:11
Thanks for reporting @MichaelArnoldOwens. Unfortunately, I can't reproduce the problem currently.
Can you please post the result of `dig howtographql.com`? Thanks!

**Comment by nikolasburk** [comment] 2018-02-14 09:16
I'm closing this issue since it's starting to age... @MichaelArnoldOwens feel free to comment or reopen if the problem still persists and we can look into it again 🙂

**Closed by nikolasburk** 2018-02-14 09:16 UTC
