### ISSUE TITLE
Solution to Prisma CRUD Exercise

### ISSUE THREAD

**Issue by athenawisdoms** [howtographql/howtographql#730] opened 2018-07-24 20:36 UTC
Hi guys,

I'm following the tutorial at  https://www.howtographql.com/graphql-js/3-a-simple-mutation/ and there's an exercise about implementing the other CRUD functions

    type Query {
    # Fetch a single link by its `id`
    link(id: ID!): Link
    }

    type Mutation {
    # Update a link
    updateLink(id: ID!, url: String, description: String): Link

    # Delete a link
    deleteLink(id: ID!): Link
    }

Is the solution found somewhere on the website? Thanks!

**Comment by B3nnyL** [comment] 2018-07-28 08:32
```
const resolvers = {
  Query: {
    info: () => `This is the API of a Hackernews Clone`,
    feed: () => links,
    link: (_, {id}) => {
      const link =  links.find(link => link.id === id)
      return link;
    }
  }
 ```

Mutation functions are  similar

**Comment by simonjoom** [comment] 2018-08-13 10:16
for Who want to learn Prisma and other who want to contribute:
We have got a ready react-native project who use prisma already setup with all techno apollo2 webpack4 react-scripts inside: 
It's here
https://github.com/simonjoom/react-native-project

Read README, We are ready to hire competent and efficient developper who use prisma API CRUD in efficient way for our project

**Comment by ragmha** [comment] 2018-09-13 12:55
I wasn't able to find a good solution but this is my solution:

```javascript
const resolvers = {
  Query: {
    info: () => `This is the API of a Hackernews Clone`,
    feed: () => links,
    link: (root, { id }) => links.find(link => link.id === id)
  },
  Mutation: {
    post: (root, args) => {
      const link = {
        id: `link-${idCount++}`,
        description: args.description,
        url: args.url
      };
      links.push(link);
      return link;
    },

    updateLink: (root, args) => {
      let updatedLink;

      links = links.map(link => {
        if (link.id === args.id) {
          updatedLink = { ...link, ...args };
          return updatedLink;
        }
        return link;
      });

      return updatedLink;
    },

    deleteLink: (root, args) => {
      const removeIndex = links.findIndex(item => item.id === args.id);
      const removedLink = links[removeIndex];
      links.splice(removeIndex, 1);

      return removedLink;
    }
  }
};

``
if anyone has a better solution, please update. thanks!

**Comment by aziz-boudi4** [comment] 2018-10-19 19:38
Here's how I implemented the updateLink (It's working but I'm not 100% if it's the best solution):
```
const resolvers = {
  Query: {
    info: () => `This is the API of a Hackernews Clone`,
    feed: () => links,
  },
  Mutation: {
    post: (root, args) => {
      const link = {
        id: `link-${idCount++}`,
        description: args.description,
        url: args.url,
      };
      links.push(link);
      return link;
    },
    updateLink: (root, args) => {
      links.forEach((link) => {
        if(link.id === args.id){
          link.id = args.id;
          link.url = args.url;
          link.description = args.description;
         }
        return link;
      });
    }
  },
};
```
and that's how I use it in GraphiQL:

```
mutation {
  updateLink(
      id: "link-3"
      description : "new description"
      url: "www.google.com"	
) {
      id 
   }
}
```

**Comment by marcoraven** [comment] 2018-12-02 12:32
@ragmha : I'm still a newbee in Javascript ; could you perhaps help me - and tell me how this part of your code works? (and for my curiosity: how is this mechanism called?)
     `updatedLink = { ...link, ...args };`
Thanks!

**Comment by swcarlosrj** [comment] 2019-02-05 21:10
Thanks @athenawisdoms for opening this issue 😄. it should be fixed. Closing this!

**Closed by swcarlosrj** 2019-02-05 21:10 UTC

**Comment by enpclark** [comment] 2019-09-19 16:51
> @ragmha : I'm still a newbee in Javascript ; could you perhaps help me - and tell me how this part of your code works? (and for my curiosity: how is this mechanism called?)
> `updatedLink = { ...link, ...args };`
> Thanks!

I had the same question, this is a spread operator. See: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
var mergedObj = { ...obj1, ...obj2 };
// Object { foo: "baz", x: 42, y: 13 }

**Comment by ricguti** [comment] 2020-05-13 18:00
Is there a way to use the link Query inside updateLink Mutation to avoid writing code to search for the link by id inside updateLink one more time?
Something like first use the link Query to bring me the link by id and now that I have the link update it.
 
Is there an "implemented by the mentors solution" for this exercise? 
The issue is closed but I haven't been able to find it in [A Simple Mutation](https://www.howtographql.com/graphql-js/3-a-simple-mutation/) or in [graphql-js repo](https://github.com/howtographql/graphql-js)

**Comment by Jawsingale** [comment] 2020-07-16 08:51
Would also like an update as I am trying to refresh through the basics.

**Comment by Mugilan-Codes** [comment] 2020-07-31 08:37
This is my solution.

```javascript
const resolvers = {
  Query: {
    info: () => `This is the API of Hackernews Clone`,
    feed: () => links,
    link: (parent, args) => links.find((link) => link.id === args.id),
  },
  Mutation: {
    post: (parent, args) => {
      const link = {
        id: `link-${idCount++}`,
        description: args.description,
        url: args.url,
      };
      links.push(link);
      return link;
    },
    updateLink: (parent, args) => {
      const link = links.find((link) => link.id === args.id);
      link.url = args.url ? args.url : link.url;
      if (args.description) {
        link.description = args.description;
      }
      return link;
    },
    deleteLink: (parent, args) => {
      const index = links.findIndex((link) => link.id === args.id);
      const link = links[index];
      links.splice(index, 1);
      return link;
    },
  },
};
```

**Comment by Ezra-Siton-UIX** [comment] 2020-08-03 18:16
"hello world" example of `Fetch a single link by its `id`
```
const { GraphQLServer } = require('graphql-yoga')

const typeDefs = `
type Query {
  get_link_by_id(id: ID!): Link!
}
type Link {
  id: ID!
  url: String!
}
`
let links = [{
    id: 'link-0',
    url: 'www.hello.com',
}]

const resolvers = {
    Query: {
      get_link_by_id: (_, {id}) => {
        const link =  links.find(link => link.id === id)
        return link;
      }
    }
}
  
const server = new GraphQLServer({
  typeDefs,
  resolvers,
})
server.start(() => console.log(`Server is running on http://localhost:4000`))
```
**GraphQL Playground:**
![image](https://user-images.githubusercontent.com/16711871/89213908-859f2480-d5ce-11ea-8c93-61c1d89c05da.png)
