### ISSUE TITLE
newVote subscription throws error in playground 

### ISSUE THREAD

**Issue by thelovesmith** [howtographql/howtographql#878] opened 2019-01-30 06:21 UTC
```
function newLinkSubscribe(parent, args, context, info) {
    return context.prisma.$subscribe.link({ mutation_in: ['CREATED'] }).node()
}

const newLink = {
    subscribe: newLinkSubscribe,
    resolve: payload => {
        return payload
    },
}

function newVoteSubscribe(parent, args, context, info) {
    return context.prisma.$subscribe.vote({ mutation_in: ['CREATED'] }).node()
}

const newVote = {
    subscribe: newVoteSubscribe,
    resolve: payload => {
        return payload
    },
}

module.exports = {
    newLink,
    newVote,
}
```

Above is my code for Subscription.js for my Graphql/Node.js tutorial
I  keep getting this error in my graphql playground: 

```
{
  "errors": [
    {
      "message": "context.prisma.$subscribe.vote is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "newVote"
      ]
    }
  ]
}
```
I've spent too much time trying to fix this and I can't seem to pinpoint the error. 
Here is the link to my repo for reference: 
[https://github.com/thelovesmith/HckrNws-Cln-GrphQL-Srvr](url)

**Comment by swcarlosrj** [comment] 2019-02-04 13:39
Thanks @thelovesmith for opening this issue 😄. It should work following the latest tutorial docs. Closing this for now, please, feel free to re-open this issue if you cannot make it work!

**Closed by swcarlosrj** 2019-02-04 13:39 UTC
Labels: :mag_right:Needs Investigation

**Comment by renshenhe** [comment] 2019-08-29 03:28
@swcarlosrj I'm still getting this issue 7 months later.  What was the cause of it? I'm not finding any fixes relating to the issue or hints at the cause. I even went through @thelovesmith 's repo with no success.
