### ISSUE TITLE
Return of subscription not working

### ISSUE THREAD

**Issue by bumblebeen** [howtographql/howtographql#204] opened 2017-08-23 07:38 UTC
Hi, 
In regards to the topic Subscriptions in Graphql.js tutorial
![rs8vzn2](https://user-images.githubusercontent.com/8120302/29603854-4343a446-8818-11e7-8ea4-6e10c63266f2.png)

I'm having the result in the above image. So far so good.
But when I add a "postedBy" field
I'm not having my expected reply.

![obj2](https://user-images.githubusercontent.com/8120302/29604116-1022edfa-8819-11e7-9876-f9c856e41ff2.PNG)

I believe I could fetch the one who posted it in a subscription
I don't think there should be a problem with Nested objects.
Also I tried to check in the resolver of type Link with an attribute postedBy
and it is not being called.

![what](https://user-images.githubusercontent.com/8120302/29604213-64f4ef5e-8819-11e7-964b-4102b616443f.PNG)

But I dont understand why it is replying that way. Can someone explain?

**Comment by klauszhang** [comment] 2017-08-24 21:23
same problem, getting error response like this:
```json
{
  "type": "data",
  "id": "6",
  "payload": {
    "errors": [
      {
        "message": "Cannot match against 'undefined' or 'null'.",
        "locations": [{ "line": 8, "column": 7 }],
        "path": ["Link", "node", "postedBy"]
      }
    ],
    "data": {
      "Link": {
        "node": {
          "url": "http://google.com",
          "description": "somplace",
          "postedBy": null
        }
      }
    }
  }
}
```
the publish method is 
```
      pubsub.publish('Link', { Link: { mutation: 'CREATED', node: newLink } });
```
with payload 
```
{ Link: 
   { mutation: 'CREATED',
     node: 
      { postedById: 599d5d499b8ef724a9efda88,
        url: 'http://google.com',
        description: 'somplace',
        _id: 599f4118319f8e5a3a6ce8b1,
        id: 599f4118319f8e5a3a6ce8b1 } } }
```
it is strange the postedById method doesn't get picked up.

**Comment by donaldsonjulia** [comment] 2017-08-29 19:04
I'm also having the same problem as @bumblebeen and I am confused as to what the problem is!

**Comment by jorissparla** [comment] 2017-09-01 07:39
Same problem as @bumblebeen and @donaldsonjulia . Has any of you been able to sort this yet?

**Comment by kevinhermawan** [comment] 2017-09-06 14:07
I think this problem because of packages version in your package.json, have you tried out to change packages version like an example? Try it and add Lodash to your package.json

**Comment by huhk-sysu** [comment] 2017-09-13 13:59
I'm using graphql@0.10.5, graphql-subscriptions@0.5.0 and apollo-server-koa@1.1.2 and meet the same problem.

In [this tutorial](https://www.howtographql.com/vue-apollo/8-subscriptions/) I found the similar queries like yours.
![image](https://user-images.githubusercontent.com/14769033/30380822-361b4d4e-98cd-11e7-82af-a61f299ca375.png)
This show that the `GraphQL.js` itself has the ability to do such nested query in a subscription, so it's strange that the `postedBy` function hasn't been called.

I guess there may be something wrong in package `apollo-server`. Maybe we can wait until new version release, which support graphql@0.11.

**Comment by marii-moe** [comment] 2017-12-04 01:55
Hey, I figured this one out today in case anyone runs into it again. 

Answer provided here: https://stackoverflow.com/questions/46907384/error-on-subscription-graphql-server/47625284#47625284

Basically the SubscriptionServer just does not have access to the dataloaders. If I can make it through the rest of the tutorial in the next few days I will probably add a pull request.

**Comment by marii-moe** [comment] 2017-12-04 01:59
Nevermind should be handled here: https://github.com/howtographql/howtographql/pull/252

**Comment by nikolasburk** [comment] 2018-02-14 10:33
Thanks a lot for pointing this out @bumblebeen! This issue should have been fixed with the latest update of the tutorial to using Prisma and `graphql-yoga`.

**Closed by nikolasburk** 2018-02-14 10:33 UTC
