### ISSUE TITLE
UNHANDLED REJECTION TypeError: Cannot read property 'internal' of undefined

### ISSUE THREAD

**Issue by itsPR** [howtographql/howtographql#163] opened 2017-07-28 13:45 UTC
Getting the following error while setting up the project locally in windows

![image](https://user-images.githubusercontent.com/2093818/28719797-d088174c-73c8-11e7-8e02-798dabb27944.png)

**Comment by marktani** [comment] 2017-07-28 13:52
What's your node/npm versions?

**Comment by itsPR** [comment] 2017-07-28 14:43
Node - V6.9.1
NPM - V4.4.4

**Comment by itsPR** [comment] 2017-07-31 16:44
Getting the following error in windows. Please help. @marktani  @nikolasburk 

![image](https://user-images.githubusercontent.com/2093818/28788268-7fca8e62-763d-11e7-979e-b309045a3827.png)

**Comment by nikolasburk** [comment] 2017-07-31 16:54
Hey @itsPR! :) Can you quickly explain what you're trying to do? Looks like you're trying to run a local version of How to GraphQL - is that what you intend or what are you trying to accomplish?

**Comment by itsPR** [comment] 2017-07-31 17:01
Yes. I'm trying to run this repository locally. but facing the above issues in windows

**Comment by nikolasburk** [comment] 2017-07-31 17:03
I haven't developed the site, maybe @timsuchanek has an idea what the issue is?

**Comment by itsPR** [comment] 2017-08-01 03:35
Please help.

Errors
![image](https://user-images.githubusercontent.com/2093818/28808307-7c5d7cca-7698-11e7-8142-104e8688a423.png)

my package.json file
`{
  "resolutions": {
    "graphql": "0.10.3"
  },
  "dependencies": {
    "algoliasearch": "^3.24.0",
    "classnames": "^2.2.5",
    "frontmatter": "^0.0.3",
    "gatsby": "^1.0.1",
    "gatsby-link": "^1.0.1",
    "gatsby-plugin-google-analytics": "^1.0.1",
    "gatsby-plugin-offline": "next",
    "gatsby-plugin-react-helmet": "^1.0.1",
    "gatsby-plugin-sharp": "next",
    "gatsby-plugin-sitemap": "next",
    "gatsby-plugin-styled-jsx": "next",
    "gatsby-remark-copy-linked-files": "next",
    "gatsby-remark-responsive-iframe": "next",
    "gatsby-remark-responsive-image": "next",
    "gatsby-remark-smartypants": "next",
    "gatsby-source-filesystem": "next",
    "gatsby-transformer-remark": "next",
    "graphcool-graphiql": "^1.8.13",
    "graphcool-styles": "^0.1.31",
    "graphql": "^0.10.3",
    "graphql-request": "^1.2.0",
    "lodash": "^4.17.4",
    "node-fetch": "^1.7.1",
    "parse-numeric-range": "^0.0.2",
    "postcss-cssnext": "^2.11.0",
    "postcss-inherit": "git+https://github.com/timsuchanek/postcss-inherit#build3",
    "postcss-simple-vars": "^4.0.0",
    "prep-cloud": "^0.0.8",
    "prismjs": "^1.6.0",
    "promise-polyfill": "^6.0.2",
    "react": "^15.5.4",
    "react-confetti": "^1.1.5",
    "react-copy-to-clipboard": "^5.0.0",
    "react-helmet": "^5.1.3",
    "react-inlinesvg": "^0.6.0",
    "react-jsx-parser": "git+https://github.com/timsuchanek/react-jsx-parser#components-object3",
    "react-particles-js": "^1.5.0",
    "react-redux": "^5.0.5",
    "react-swipeable-views": "^0.12.3",
    "react-transition-group": "^1.2.0",
    "redux": "^3.7.1",
    "redux-localstorage": "rc",
    "redux-localstorage-filter": "^0.1.1",
    "redux-logger": "^3.0.6",
    "relay-compiler": "^1.1.0",
    "styled-jsx": "git+https://github.com/timsuchanek/styled-jsx#build",
    "styled-jsx-postcss": "git+https://github.com/timsuchanek/styled-jsx-postcss#build3",
    "ts-loader": "^2.2.0",
    "tslint-config-prettier": "^1.1.0",
    "tslint-eslint-rules": "^4.1.1",
    "tslint-react": "^3.0.0",
    "typescript": "2.2.1",
    "unist-util-visit": "^1.1.1",
    "youtube-embed-video": "^1.0.2"
  },
  "scripts": {
    "start": "gatsby develop",
    "build": "gatsby build",
    "precommit": "lint-staged",
    "prettier": "prettier --single-quote --no-semi --trailing-comma all --write *.{ts,tsx}"
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "prettier --single-quote --no-semi --trailing-comma all --write",
      "tslint",
      "git add"
    ]
  },
  "devDependencies": {
    "@types/node": "^8.0.2",
    "@types/react-router": "^4.0.11",
    "flowtype-loader": "^0.2.2",
    "lint-staged": "^4.0.0",
    "postcss-discard-comments": "^2.0.4",
    "prettier": "^1.4.4",
    "tslint": "^5.4.3",
    "tslint-config-standard": "^6.0.1",
    "tslint-loader": "^3.5.3",
    "xmldom": "git+https://github.com/timsuchanek/xmldom#node-list"
  }
}`

**Comment by itsPR** [comment] 2017-08-01 04:04
![image](https://user-images.githubusercontent.com/2093818/28808792-862c2a68-769c-11e7-989f-a74547608712.png)
![image](https://user-images.githubusercontent.com/2093818/28808797-8d2720f2-769c-11e7-9ac3-b6c50d15f117.png)
the repository yarn.lock file completely works fine in Ubuntu. but only in windows i am getting the above errors
So, just want to know the compatible gatsby version for windows

**Comment by itsPR** [comment] 2017-08-04 09:15
Please help

**Comment by nikolasburk** [comment] 2018-02-14 09:32
Hey @itsPR, did you find a solution to this problem? 🙂  If it's ok, I'm going to close the issue as it's starting to age. Also note that we'll update the entire site soon, so that might fix the problem anyways 👍

**Closed by nikolasburk** 2018-02-14 09:32 UTC

**Comment by itsPR** [comment] 2018-02-19 17:23
@nikolasburk Thanks for the update. could you please let me know when you are planning release the new site?
