### ISSUE TITLE
Subscriptions not working (graphql.js - Subscriptions)

### ISSUE THREAD

**Issue by Musbell** [howtographql/howtographql#456] opened 2018-01-25 14:06 UTC
Subscriptions not working after sending subscribed mutations i.e. **newLink** and **newVote**

**Comment by iquabius** [comment] 2018-01-25 18:27
It didn't work for me either.

**Comment by azizuysal** [comment] 2018-01-27 01:37
Ditto.

**Comment by nyoung697** [comment] 2018-01-29 01:11
I was able to get it working by removing the where clause in the Subscription.js file:

    const newLink = {
      subscribe: async (parent, args, ctx, info) => {
        return ctx.db.subscription.link(
          { },
          info
        )
      },
    }

I'm not sure why that mutation_in isn't working...  Haven't had a chance to dig around.

**Comment by nntai** [comment] 2018-01-31 00:03
It's not working for me too
Follow issue on prisma: https://github.com/graphcool/prisma/issues/1734

**Comment by eyal0803** [comment] 2018-02-05 19:21
Looks like there was a PR (#475) which fixed the backend tutorial.
Anyway, like @nyoung697 sayd, just remove the `where` clause.

**Comment by thelovesmith** [comment] 2019-01-30 05:41
```
function newVoteSubscribe(parent, args, context, info) {
    return context.prisma.$subscribe.vote({ 
        mutation_in: ['CREATED'] 
    }).node()
}

const newVote = {
    subscribe: newVoteSubscribe,
    resolve: payload => {
        return payload
    },
}
```

for some reason this code keeps giving me an error in the playground, it keeps returning "context.prisma.$subscribe.vote" is not a function

**Comment by swcarlosrj** [comment] 2019-02-05 21:23
Thanks @Musbell for opening this issue 😄. It should be fixed. Closing this!

**Closed by swcarlosrj** 2019-02-05 21:23 UTC

**Comment by gentleShark** [comment] 2019-03-04 04:23
@swcarlosrj the newVote subscription still doesn't work like @thelovesmith mentioned. newVote is a recognized subscription in the playground but the vote() function is not created by prisma on the $subsciption object...thus the resolver fails with the error: "message": "context.prisma.$subscribe.vote is not a function" 

I wonder if the problem is related to Vote being a lookup table?

**Comment by jonatasbaldin** [comment] 2019-03-10 19:11
Hey @swcarlosrj, can you take a look on this?

**Comment by rootandleaves** [comment] 2019-09-22 14:58
same problem..any solution ?

**Comment by blacksrc** [comment] 2020-01-31 12:58
If you are following the howtographql.com tutorial. Make sure that,
```
type Vote {
  id: ID! @id
  link: Link!
  user: User!
}
```
exists in your `datamodel.prisma` file. And do not forget to deploy it before starting the server again:
```
prisma deploy
```
