### ISSUE TITLE
TypeError: context.db.mutation.createUser is not a function

### ISSUE THREAD

**Issue by christinetran825** [howtographql/howtographql#768] opened 2018-08-21 20:05 UTC
Hello. I'm new to How To GraphQL. I was working on the tutorial on Node, when I got stuck on Step Authentication.

When running node src/index.js, I get the following error.

`TypeError: context.db.mutation.createUser is not a function
   at signup (/Users/christinetran/Documents/GitHub/hackernewsnode/src/resolvers/Mutation.js:9:42)`

I followed the steps correctly, so I'm not sure what the issue is. Here is the Mutation file. It's just like the tutorial.

```const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const { APP_SECRET, getUserId } = require('../utils')

function post(parent, args, context, info) {
  const userId = getUserId(context)
  return context.db.mutation.createLink(
    {
      data: {
        url: args.url,
        description: args.description,
        postedBy: { connect: { id: userId } },
      },
    },
    info,
  )
}

async function signup(parent, args, context, info) {
  // 1
  const password = await bcrypt.hash(args.password, 10)
  // 2
  const user = await context.db.mutation.createUser({
    data: { ...args, password },
  }, `{ id }`)

  // 3
  const token = jwt.sign({ userId: user.id }, APP_SECRET)

  // 4
  return {
    token,
    user,
  }
}

async function login(parent, args, context, info) {
  // 1
  const user = await context.db.query.user({ where: { email: args.email } }, ` { id password } `)
  if (!user) {
    throw new Error('No such user found')
  }

  // 2
  const valid = await bcrypt.compare(args.password, user.password)
  if (!valid) {
    throw new Error('Invalid password')
  }

  const token = jwt.sign({ userId: user.id }, APP_SECRET)

  // 3
  return {
    token,
    user,
  }
}

module.exports = {
    signup,
    login,
    post,
}```

**Comment by christinetran825** [comment] 2018-08-21 20:43
I resolved it... I forgot to `prisma deploy`

Please mark this resolved and closed

**Comment by mrimran** [comment] 2018-10-04 18:56
I'm facing the same issue and I ran `prisma deploy` too. But the problem is still there.

**Comment by mrimran** [comment] 2018-10-04 19:12
I fixed it too I was missing the following code snippet, in `database/prisma.yml` file

```
# Deploy hook
hooks:
  post-deploy:
    - graphql get-schema --project database
```

**Comment by pugson** [comment] 2018-12-30 22:54
Running into the same issue. `prisma deploy` did not help. My _Mutation.js_ is the same as the one in the tutorial.

**Comment by swcarlosrj** [comment] 2019-02-04 13:48
Thanks for opening this issue 😄. It seems to be solved following the latest tutorial docs. Closing this!

**Closed by swcarlosrj** 2019-02-04 13:48 UTC
Labels: :mag_right:Needs Investigation
