### ISSUE TITLE
GraphQL misconfiguration in Prisma tutorial

### ISSUE THREAD

**Issue by Nargonath** [howtographql/howtographql#738] opened 2018-07-28 12:46 UTC
Thanks for the great tutorials, they are awesome!

I think there is a little quirk in the chapter `Connecting server and database with Prisma bindings`. When creating the `.graphqlconfig.yml` file at the root of the project, the path to the `prisma.yml` file is off. See below:
```yml

projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml

```
IMO the `prisma` property should be `prisma: src/database/prisma.yml` instead, at least I had to fix it for it to work when calling `prisma deploy`.

I'll make a PR to fix it, thanks again. 😉

**Comment by GiantZOC** [comment] 2018-08-16 16:02
I think the prisma property is correct.  You probably put your database folder in hackernews-node/src/database instead of hackernews-node/database which was intended by the tutorial.

**Comment by swcarlosrj** [comment] 2019-02-04 13:51
Thanks @Nargonath for opening this issue 😄. It seems to be solved following the latest tutorial docs. Closing this for now, please, feel free to open an issue if you cannot make it work!

**Closed by swcarlosrj** 2019-02-04 13:51 UTC

**Comment by Nargonath** [comment] 2019-02-04 16:00
Oups sorry I forgot to come back answering the issue but yeah it was my mistake, I guess I misunderstand the docs. Glad that the docs were improved then. Thanks. 👍
